version: "3.8"
services:
  db:
    image: postgres:15.4
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: mrubio
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /home/mrubio/postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: mariorubiodev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: mrubio
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"

